[package]
name = "observer_test"
version = "0.1.0"
authors = ["barba"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.3.0"
bevy_tilemap = "0.1.1"
rand = "0.7.3"